services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      # Mount App_Data directory for persistent data
      - ./App_Data:/app/App_Data
#    depends_on:
#      - db
    networks:
      - ubixar-network
    restart: unless-stopped

  # PostgreSQL database service
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=gateway
      - POSTGRES_USER=gateway
      - POSTGRES_PASSWORD=gateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: mount init scripts
      - ./config/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    networks:
      - ubixar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gateway -d gateway"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  ubixar-network:
    driver: bridge