# Name of your application. Used to uniquely configure containers.
service: ubixar

# Name of the container image.
image: servicestack/ubixar.com
  
<% require "dotenv"; Dotenv.load(".env") %>
# Environment variables to set in the container.
env:
  clear:
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: true # Required for use of ASP.NET Core with Kamal-Proxy.
  secret:
    - COMFY_DB_CONNECTION

# Deploy to these servers.
servers:
  # IP address of server, optionally use env variable.
  web:
    - 5.78.128.205
#   - <%= ENV['KAMAL_DEPLOY_IP'] %>


# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption.
proxy:
  ssl: true
  host: ubixar.com
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  app_port: 8080
  response_timeout: 30  # Reduce timeout to fail faster and help diagnose
  forward_headers: true
  buffering:
    requests: false
    responses: false
  # Add detailed logging to help diagnose the issue
  logging:
    request_headers:
      - User-Agent
      - Connection
      - Upgrade
      - Accept
      - Accept-Encoding
      - Content-Length
      - Host
    response_headers:
      - Content-Type
      - Connection
      - Upgrade
      - Content-Length
      - Server

    
# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

volumes:
  - "/opt/docker/ubixar.com/App_Data:/app/App_Data"

# Kamal 2 automatically creates and uses the 'kamal' network
# No additional docker options needed for networking

accessories:
  postgres:
    image: postgres
    host: 5.78.128.205
    port: "5432:5432"
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: ubixar
        DB_HOST: 0.0.0.0
        DB_PORT: 5432
      secret:
        - POSTGRES_PASSWORD
    directories:
      - /opt/docker/ubixar.com/postgres:/var/lib/postgresql/data
      - /opt/docker/ubixar.com/initdb.d:/docker-entrypoint-initdb.d
  backup:
    image: ghcr.io/servicestack/backup-postgres:latest
    host: 5.78.128.205
    env:
      clear:
        POSTGRES_HOST: ubixar-postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: ubixar
        BACKUP_INTERVAL: 86400  # 24 hours
        RETENTION_DAYS: 7       # Keep local backups for 7 days
        S3_RETENTION_DAYS: 30   # Keep S3 backups for 30 days
        S3_BUCKET: backups
        S3_PREFIX: ubixar
        AWS_DEFAULT_REGION: auto
      secret:
        - POSTGRES_PASSWORD
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_ENDPOINT_URL
    directories:
      - /opt/docker/ubixar.com/backups:/backups
