#!/bin/bash

DB=${1:-app}
USER=${2:-app}
PASSWORD=${3:-p@55wOrd}

cat <<EOF
CREATE DATABASE "$DB";
CREATE USER "$USER" WITH ENCRYPTED PASSWORD '$PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE "$DB" TO "$USER";

-- Connect to the newly created database to set additional permissions
\c "$DB"

GRANT ALL ON SCHEMA public TO "$USER";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$USER";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$USER";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "$USER";

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO "$USER";

ALTER DATABASE "$DB" OWNER TO "$USER";
EOF